### ISSUE TITLE
Evaluate other sites that can be scraped.

### ISSUE THREAD

**Issue by grigio888** [grigio888/MangaGrid#67]
## Briefing

We'll start to expanding our sources, scraping others sites.

## To be doned

As starting point, we will make a lists of website that can be scrapped using `requests_html`.
Connection could be maded with him or `cloudscraper`.

**Comment by phzsantos** [comment]
Found some.

https://mangayabu.top/
https://muitomanga.com/
https://leitor.net/
https://yesmangas1.com/
https://darkscans.com/
https://mangagg.com/
https://www.topmanhua.com/
https://firemangas.com/
https://mangahosted.com/

**Comment by grigio888** [comment]
Ok.
Which of them can be scraped without needing to render the javascript?

We should divide this list in two categories, to make priority on those who doesn't need to be rendered (cuz it's much more easy and less taxative to the server).

**Comment by phzsantos** [comment]
Work without js:
https://mangayabu.top/ (only last updates)
https://mangahosted.com/ (full)

Need js: 
https://muitomanga.com/
https://leitor.net/
https://yesmangas1.com/
https://darkscans.com/
https://mangagg.com/
https://www.topmanhua.com/
https://firemangas.com/

**Comment by grigio888** [comment]
We will start with `https://mangahosted.com/`, cuz its the more easy.

**Comment by grigio888** [comment]
## Tasks:

### Where to:
- [ ] Module have to be created in `manga/modules/`.

### How to:
Module must have the following methods:
- [ ] `__init__` and must have:
  - [ ] `source_slug`
  - [ ] `source_language`
  - [ ] `source_url`

- [ ] `refresh_routine`
  - [ ] Pointing to `site_latest_update`

- [ ] `site_latest_update` and must export the following model:
_This method is only for feeding the jsons for latest updated and the auto update task_
```
{
    'chapter_link' : STRING,
    'chapter_title' : STRING,
    'chapter_updated_on_source' : DATETIME TRANSFORMED TO STRING,
    'manga_author' : STRING,
    'manga_image' : STRING,
    'manga_link' : self.link_manga_viewer(STRING USED ON MANGA_SLUG),
    'manga_slug' : STRING,
    'source_language' : self.source_language,
    'source_url' : self.source_url,
    'source_slug' : self.source_slug,
}
```

- [ ] `site_search` and must export the following model:
_This method is to feed the search section of the site_
```
{
    'chapter_link' : STRING,
    'chapter_title' : STRING,
    'chapter_updated_on_source' : DATETIME TRANSFORMED TO STRING,
    'manga_author' : STRING,
    'manga_image' : STRING,
    'manga_link' : self.link_manga_viewer(STRING USED ON MANGA_SLUG),
    'manga_slug' : STRING,
    'manga_title' : STRING,
    'source_language' : self.source_language,
    'source_url' : self.source_url,
    'source_slug' : self.source_slug,
}
```

- [ ] `manga_info` and must export the following model:
```
{
    'manga_author' : [
        STRING,
        STRING,
        ...
    ],
    'manga_description' : STRING,
    'manga_genre' : [
        STRING,
        STRING,
        ...
    ],
    'manga_image' : STRING,
    'manga_slug' : STRING,
    'manga_status' : STRING,
    'manga_title' : STRING,
    'manga_updated' : DATETIME,
    'manga_views' : STRING,
    'chapters' : [
        {
            'chapter_link' : self.link_chapter_viewer(STRING FROM CHAPTER_SLUG),
            'chapter_slug' : STRING,
            'chapter_title' : STRING,
            'chapter_updated_on_source' : DATETIME
        },
        {
            'chapter_link' : self.link_chapter_viewer(STRING FROM CHAPTER_SLUG),
            'chapter_slug' : STRING,
            'chapter_title' : STRING,
            'chapter_updated_on_source' : DATETIME
        },
        ...
    ],
    'source_language' : self.source_language,
    'source_url' : self.source_url,
    'source_slug' : self.source_slug,
}
```

- [ ] `manga_chapter` and can export one of the followings:
  - If the manga is indexed:
  _Notice that if the manga is indexed, most of this information is provided by the method `serialize()`_
  _The same occour for the chapter_
```
{
    'manga_id': INT,
    'manga_slug': STRING,
    'manga_title': STRING,
    'manga_image': STRING,
    'manga_status': INT (FOREIGN KEY),
    'manga_updated': DATETIME,
    'manga_views': STRING,
    'manga_description': STRING,
    'manga_source': INT (FOREIGN KEY),
    'manga_created_at': DATETIME,
    'manga_updated_at': DATETIME,
    'manga_link': STRING,
    'chapter_id': INT,
    'chapter_slug': STRING,
    'chapter_title': STRING,
    'chapter_link': STRING,
    'chapter_manga_id': INT (FOREIGN KEY),
    'chapter_manga_title': STRING,
    'chapter_created_at': DATETIME,
    'chapter_updated_at': DATETIME,
    'chapter_updated_on_source': DATETIME,
    'chapter_prev': STRING,
    'chapter_next': STRING,
    'chapter_content': [
        STRING,
        STRING,
        ...
    ]
}
```
  - If the manga it´s not indexed:
```
{
    'manga_title': STRING,
    'manga_link': STRING,
    'chapter_title': STRING,
    'chapter_prev': STRING,
    'chapter_next': STRING,
    'chapter_content': [
        STRING,
        STRING,
        ...
    ]
}
```
